import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const mainFontFAmily = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-family-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${mainFontFAmily.variable}`}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
